name: 🧪 Lumen Logger CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1️⃣ — Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2️⃣ — Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3️⃣ — Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install build pytest pytest-cov
          pip install -e .

      # Step 4️⃣ — Run tests with coverage
      - name: Run pytest with coverage
        run: |
          pytest -v \
            --cov=lumen_logger \
            --cov-report=term-missing \
            --cov-report=xml \
            --cov-fail-under=90

      # Step 5️⃣ — Upload coverage results to GitHub summary (optional)
      - name: Upload coverage summary
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      # Step 1️⃣ — Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2️⃣ — Build wheel and sdist
      - name: Build package
        run: |
          pip install build
          python -m build

      # Step 3️⃣ — Upload build artifacts
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lumen-logger-dist
          path: dist/*

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
